sudo: required

services:
  - docker

before_install:
  - chmod a+x ./.travis/before_install.sh
  - ./.travis/before_install.sh

script:
  - chmod a+x ./.travis/build.sh
  - ./.travis/build.sh

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli 
# and then `travis set ..` or go to the travis
# page of your repository and then change the 
# environment in the settings pannel.
#after_success:
#  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
#      make push-image ;
#    fi

# don't notify me when things fail
notifications:
  email: false
