#!/bin/bash

set -e
# set -x

mv /usr/sbin/policy-rc.d.disabled /usr/sbin/policy-rc.d

update-rc.d mountkernfs.sh defaults
apt-get update
apt-get -y --no-install-recommends install makepasswd

apt-get -y -u dist-upgrade
update-rc.d -f mountkernfs.sh remove

apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

/usr/local/bin/docker-wipelogs

mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled
